/**
 * Generates the Open Graph share cards as real .png files.
 *
 * Run with:  node scripts/make-og.mjs
 *
 * Why this exists rather than Next's `opengraph-image.tsx` convention:
 * that convention emits EXTENSIONLESS files (…/analogies/<slug>/opengraph-image).
 * A static host infers content type from the extension, so those get served as
 * `application/octet-stream`, and link-preview scrapers refuse to render them.
 * A Vercel `headers` rule does not fix it — the host will not override
 * Content-Type on a static asset. Verified against the live deployment.
 *
 * Generating plain `.png` files into /public sidesteps the whole problem and
 * works identically on Vercel, GitHub Pages, Netlify, or anywhere else.
 *
 * The output is committed, so no font or rasteriser is needed at deploy time.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

import { ANALOGIES } from "../src/content/analogies.ts";
import { CATEGORY_LABELS } from "../src/content/types.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public", "og");

const W = 1200;
const H = 630;
const PAD = 72;
const INNER = W - PAD * 2;

const BG = "#0b0d0f";
const TEXT = "#f2f0eb";
const MUTED = "#9ba4ae";
const SUBTLE = "#7d8691";
const GAIN = "#10b981";

const FONT = "Segoe UI, Inter, Helvetica, Arial, sans-serif";

/** SVG has no text layout engine, so wrap greedily using an average glyph width. */
function wrap(text, fontSize, maxWidth, maxLines = 3) {
  const perChar = fontSize * 0.5;
  const maxChars = Math.floor(maxWidth / perChar);
  const words = String(text).split(/\s+/);
  const lines = [];
  let line = "";

  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (candidate.length <= maxChars) {
      line = candidate;
    } else {
      if (line) lines.push(line);
      line = word;
      if (lines.length === maxLines) break;
    }
  }
  if (line && lines.length < maxLines) lines.push(line);

  if (lines.length === maxLines && words.join(" ").length > lines.join(" ").length) {
    lines[maxLines - 1] = lines[maxLines - 1].replace(/[.,;:]?$/, "…");
  }
  return lines;
}

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function lines(text, { x, y, size, fill, weight = 400, lineHeight = 1.25, maxLines = 3, spacing = 0 }) {
  return wrap(text, size, INNER, maxLines)
    .map(
      (l, i) =>
        `<text x="${x}" y="${y + i * size * lineHeight}" font-family="${FONT}" font-size="${size}" font-weight="${weight}" fill="${fill}"${spacing ? ` letter-spacing="${spacing}"` : ""}>${esc(l)}</text>`
    )
    .join("");
}

function card({ category, headline, caption, title }) {
  // Headline shrinks for long strings so it never overruns the card.
  const headlineSize = headline.length > 22 ? 62 : headline.length > 12 ? 88 : 128;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="${W}" height="${H}" fill="${BG}"/>
  <rect x="0" y="0" width="${W}" height="6" fill="${GAIN}"/>
  ${category ? `<text x="${PAD}" y="${PAD + 30}" font-family="${FONT}" font-size="22" fill="${SUBTLE}" letter-spacing="4">${esc(category.toUpperCase())}</text>` : ""}
  ${lines(headline, { x: PAD, y: PAD + 150, size: headlineSize, fill: GAIN, maxLines: 1 })}
  ${lines(caption, { x: PAD, y: PAD + 215, size: 30, fill: MUTED, maxLines: 2 })}
  ${lines(title, { x: PAD, y: H - PAD - 96, size: 46, fill: TEXT, maxLines: 2 })}
  <text x="${PAD}" y="${H - PAD}" font-family="${FONT}" font-size="24" fill="${SUBTLE}">Positive Sum — every analogy states where it breaks down</text>
</svg>`;
}

async function main() {
  await mkdir(OUT, { recursive: true });

  for (const a of ANALOGIES) {
    const svg = card({
      category: CATEGORY_LABELS[a.category],
      headline: a.headline,
      caption: a.headlineCaption,
      title: a.title,
    });
    await sharp(Buffer.from(svg)).png().toFile(join(OUT, `${a.slug}.png`));
  }
  console.log(`  wrote ${ANALOGIES.length} analogy cards`);

  // Site-wide default, used by the home page and anything without its own card.
  const defaultSvg = card({
    category: "",
    headline: "51.6%",
    caption: "of all US stocks since 1925 lost money over their entire listed life",
    title: "Investing, gambling, and the difference between them",
  });
  await sharp(Buffer.from(defaultSvg)).png().toFile(join(OUT, "default.png"));
  console.log("  wrote default card");

  await writeFile(
    join(OUT, "README.md"),
    "Generated by `node scripts/make-og.mjs`. Committed deliberately: they are plain .png files so every host serves them with the right content type.\n"
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
